name: Build for macOS

on:
  push:
    branches: [ feature/fruity_v2 ]
  pull_request:
    branches: [ feature/fruity_v2 ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { image_suffix: "" } # arm64
          - { image_suffix: "-intel" } # x86_64
    runs-on: macos-26${{ matrix.image_suffix }}
    steps:
    - uses: actions/checkout@v6
    - run: brew install eigen@3 pkg-config cmake vulkan-loader glslang && brew link --force eigen@3
    - run: cmake -B build -DXRT_FEATURE_SERVICE=OFF -DXRT_MODULE_IPC=OFF .
    - run: cmake --build build
    - run: |
        mkdir -p dest
        python3 .github/utils/change_load_path.py build/src/xrt/targets/openxr/libopenxr_monado.dylib dest/
    - uses: actions/upload-artifact@v7
      with:
        name: build-${{ runner.arch }}
        path: dest/*.*
  merge:
    needs: build
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v6
      with:
        sparse-checkout: .github/
    - uses: actions/download-artifact@v8
      with:
        path: dest
        pattern: build-*
    - run: mkdir merged && python3 .github/utils/merge_binaries.py dest/ merged/
    - uses: actions/upload-artifact@v7
      with:
        name: merged
        path: merged/*.*
